import { createApp } from 'vue';
import './css/style.css';
import App from './App.vue';
import router from './router';
import TheHeader from './components/TheHeader.vue';
import TheFooter from './components/TheFooter.vue';
import TheBanner from './components/TheBanner.vue';
const app = createApp(App);
app.component('TheHeader', TheHeader);
app.component('TheFooter', TheFooter);
app.component('TheBanner', TheBanner);
app.use(router);
app.mount('#app');
